[package]
name = "rayca"
version = "0.2.0"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window",
    "Document",
    "Performance",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "ImageData"
]

[dependencies]
gltf = "1.0.0"
num-traits = "0.2.14"
owo-colors = { version = "3.3.0", features = ["supports-colors"] }
png = "0.17.5"
rayon = { version = "1.5.1", optional = true }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
instant = { version = "0.1.12", features = [ "wasm-bindgen", "inaccurate" ] }


[features]
parallel = [ "rayon" ]
