[package]
name = "rayca"
version = "0.1.0"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
edition = "2018"
license = "MIT"

[dependencies]
gltf = "1.0.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
png = "0.17.7"
