[package]
name = "rayca"
version = "0.1.0"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
edition = "2018"
license = "MIT"

[dependencies]
gltf = "1.0.0"
num-traits = "0.2.15"
owo-colors = { version = "3.4.0", features = ["supports-colors"] }
png = "0.17.5"
rayon = "1.5.3"
