name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check
      run: cargo check --release

    - name: Test
      run: |
        git submodule update --init
        cargo test --release

    - name: Profile
      run: |
        cargo install flamegraph
        sudo sysctl -w kernel.perf_event_paranoid=-1
        sudo sysctl -w kernel.kptr_restrict=0
        sudo chmod 666 /proc/kallsyms
        CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph --no-default-features \
          --package rayca-soft --test test -- cube_over_plane
        mkdir rayca-soft/www/dist
        mv flamegraph.svg rayca-soft/www/dist/

    - name: Web
      run: |
        cargo install wasm-pack
        cd rayca-soft
        wasm-pack build -- --no-default-features
        cd www
        npm install
        npm run build
        cp ../target/artifacts/*.png dist

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        external_repository: fahien/rayca-web
        personal_token: ${{ secrets.RAYCA_WEB }}
        publish_dir: www/dist
