name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: jetli/wasm-pack-action@v0.4.0

    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        components: rust-src

    - uses: actions-rs/install@v0.1
      with:
        crate: flamegraph
        version: latest
        use-tool-cache: true

    - name: Check
      run: cargo check --release

    - name: Test
      run: |
        git submodule update --init
        cargo test --release

    - name: Profile
      run: |
        sudo sysctl -w kernel.perf_event_paranoid=-1
        sudo sysctl -w kernel.kptr_restrict=0
        sudo chmod 666 /proc/kallsyms
        mkdir rayca-soft/www/static
        CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph --release --package rayca-soft \
          --test test --output rayca-soft/www/static/flamegraph.svg -- cube_over_plane

    - name: Web
      run: |
        cd rayca-soft/www
        npm install
        npm run release
        cp ../../tests/artifact/*.png dist

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        external_repository: fahien/rayca-web
        deploy_key: ${{ secrets.RAYCA_WEB }}
        publish_dir: rayca-soft/www/dist
